services:
  daemon:
    build: ./daemon/
    command: sh -c "sleep 5s ; python ./main.py"
    ports:
      - '4000:4000'
    depends_on:
      - pythonapp
    volumes:
      - ./daemon:/app
    networks:
      - daemon_network

  pythonapp:
    build: ./python/
    command: sh -c "sleep 5s ; python ./app.py"
    ports:
      - '5001:5001'
    depends_on:
      - mysql
    volumes:
      - ./python:/app
    networks:
      - daemon_network

  mysql:
    build: ./db/
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQLDATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD}
    ports:
      - '3308:3306'
    volumes:
      - ./data:/app
    networks:
      - daemon_network

networks:
  daemon_network:
    driver: bridge
