services:
  daemon:
    build: ./daemon/
    command: sh -c "sleep 5s ; python ./main.py"
    ports:
      - '4000:4000'
    depends_on:
      - pythonapp

  pythonapp:
    build: ./python/
    command: sh -c "sleep 5s ; python ./app.py"
    ports:
      - '5000:5000'
    depends_on:
      - mysql

  mysql:
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: 'queue_db'
      MYSQL_ROOT_PASSWORD: '12976'
    ports:
      - '3306:3306'
